theme: jekyll-theme-tactile
title: Jack Rawlings
description: I am beginning my blogging journey because I personally want to take the opportunity to share my learnings and thoughts. Also, I find writing an effective hobby in understand my own thoughts and actions. I'm relatively reflective in nature, I've kept a journal since 16, and have benefitted from the clarity drawn from intrespection. My goal here is to help others learn from lessons I've faced.
